[options]
addons_path=/home/antoine/Documents/Odoo/odoo19/addons,/home/antoine/Documents/Odoo/odoo19/design-themes,/home/antoine/Documents/Odoo/odoo19/enterprise,/home/antoine/Documents/Odoo/odoo19/clients/groupeuniverspharmacie
data_dir=/home/antoine/Documents/Odoo/odoo19/store/gup_v19
admin_passwd=admin
db_name=gup_v19
http_port=1234
load_language=fr_FR
db_host = 127.0.0.1
db_port = 5432
db_user = odoo
db_password = odoo
Sur les abonnements, des tâches sont créées automatiquement. Lors de la validation d'une tâche, une nouvelle est créée automatiquement. 

En V16 actuelle la nouvelle tâche prend une date d'échéance à N-1 par rapport à la date choisie dans la popup. Le fonctionnement est à l'envers.





Le bon fonctionnement, existant à l'heure actuelle en V14 est le suivant : 

Lors de la validation d'une tâche une popup s'ouvre, permettant de choisir une date ; 



Cette date vient modifier automatiquement la date limite (date d'échéance) de la tâche que l'on vient de valider.



La nouvelle tâche est ensuite créée en reprenant la date d'échéance de la tâche validé + la récurrence du modèle d'opération concerné. 

Exemple : Validation d'une tâche, date renseignée = 20/12/2024 / La tâche validé prend la date du 20/12/2024 en date d'échéance / La nouvelle tâche prend une date d'échéance au 20/12/2025, calcul = Date de la tâche validée 20/12/2024 + Récurrence du modèle d'opération (1 an) Donc 20/12/2024





Exemple de deux tâches : 

1 - Tâche terminée

2 - Nouvelle tâche créé automatiquement en cours, date d'échéance : 20/08/2025
smtp = localhost
smtp_port = 1025
