[options]
addons_path = /home/antoine/Documents/Odoo/odoo19/addons,/home/antoine/Documents/Odoo/odoo19/design-themes,/home/antoine/Documents/Odoo/odoo19/enterprise,/home/antoine/Documents/Odoo/odoo19/clients/ssi,/home/antoine/Documents/Odoo/odoo19/clients/ssi/omd_base_enterprise
data_dir = /home/antoine/Documents/Odoo/odoo19/store/ssi_test_v19
admin_passwd = $pbkdf2-sha512$600000$ivH./z8nJITwfm8tpTQmpA$PX1BIc6BeEd1F76zGGaWyqWpsn7V3RKq09rDTRGz4rb/j.xd3EvHoa.KCKiOuY.RsO/Mt3rTyIlt5wmTh8dmRQ
db_host = 127.0.0.1
db_port = 5432
db_user = odoo
db_password = odoo
db_name = prod-ssi-v19-fresh
http_port = 1234
load_language = fr_FR
